/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import com.team.entry.Member;
import com.team.entry.Team;
import com.team.service.MemberService;
import com.team.service.TeamService;
import com.team.util.StringUtil;

/**
 *
 * @author Administrator
 */
public class EditTeam extends javax.swing.JFrame {
	
	public static Team team = new Team();
	private TeamService teamService = new TeamService();

    /**
     * Creates new form EditTeam
     */
    public EditTeam() {
    	super("队伍");
        initComponents();
    }
    
    MemberService memberService = new MemberService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("队名：");

        jLabel2.setText("队长：");
        
        String[] names = memberService.getNames();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(names));
        
        jButton1.setText("确定");

        jButton2.setText("返回");
        
        if(StringUtil.isNotBlank(team.getName()))
        {
        	jTextField1.setText(team.getName());
        	
        	Member member = team.getLeader();
        	if(null == team)
        	{
        		jComboBox1.setSelectedItem("未分组");
        	}
        	else
        	{
        		jComboBox1.setSelectedItem(member.getName());
        	}
        }
        
        jButton1.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
				commit();
			}
		});
        
        jButton2.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
				back();
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addComponent(jComboBox1, 0, 148, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        this.setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    protected void back()
	{
		this.dispose();
		new TeamManageFrame();
	}

	protected void commit()
	{
		String name = jTextField1.getText();
		String leader = (String) jComboBox1.getSelectedItem();
		if(StringUtil.isBlank(name))
    	{
    		JOptionPane.showMessageDialog(this, "请将信息填完整！", "错误提示", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
		Member member = memberService.get(leader);
		Team team = new Team();
		team.setLeader(member);
		team.setName(name);
		
		if(StringUtil.isNotBlank(EditTeam.team.getName()))
    	{
    		teamService.update(EditTeam.team.getId(),team);
    		JOptionPane.showMessageDialog(this, "修改队伍成功!", "成功", JOptionPane.INFORMATION_MESSAGE);
    		this.dispose();
    		new TeamManageFrame();
    	}
    	else
    	{
    		teamService.add(team);
    		JOptionPane.showMessageDialog(this, "添加队伍成功!", "成功", JOptionPane.INFORMATION_MESSAGE);
    		this.dispose();
    		new TeamManageFrame();
    	}
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
