/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.gui.firsttype.FirstTypeManageFrame;
import com.gui.product.ProductManageFrame;
import com.gui.secondtype.SecondTypeManageFrame;
import com.gui.user.UserManageFrame;

/**
 *
 * @author Administrator
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
    	super("菜单");
        initComponents();
    }
    
    private void manageUser()
    {
    	this.dispose();
    	new UserManageFrame();
    }
    private void manageFirstType()
    {
    	this.dispose();
    	new FirstTypeManageFrame();
    }
    private void manageSecondType()
    {
    	this.dispose();
    	new SecondTypeManageFrame();
    }
    private void manageProduct()
    {
    	this.dispose();
    	new ProductManageFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ctrlButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("菜单");

        jButton1.setText("用户管理");

        jButton2.setText("大类管理");

        jButton3.setText("小类管理");
        
        jButton4.setText("商品管理");
        
        jButton1.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
				manageUser();
			}

		});
        
        jButton2.addActionListener(new ActionListener()
        {
        	
        	public void actionPerformed(ActionEvent arg0)
        	{
        		manageFirstType();
        	}
        });
        
        jButton3.addActionListener(new ActionListener()
        {
        	
        	public void actionPerformed(ActionEvent arg0)
        	{
        		manageSecondType();
        	}
        });
        
        jButton4.addActionListener(new ActionListener()
        {
        	
        	public void actionPerformed(ActionEvent arg0)
        	{
        		manageProduct();
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            )))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addGap(20, 20, 20)
                .addComponent(jButton4)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        
        this.setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton ctrlButton;
    
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
