/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui.secondtype;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import com.dao.SecondTypeDao;
import com.dao.impl.SecondTypeDaoImpl;
import com.entity.SecondType;
import com.gui.MenuFrame;
import com.mysql.fabric.xmlrpc.base.Member;

/**
 *
 * @author Administrator
 */
public class SecondTypeManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form TeamManageFrame
     */
    public SecondTypeManageFrame() {
    	super("用户管理");
        initComponents();
    }
    
    public SecondTypeDao SecondTypeDao = new SecondTypeDaoImpl();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
        	public String[] getNames(){
        		List<SecondType> SecondTypes = SecondTypeDao.listQuery(null, null, null, null);
        		String[] names = new String[SecondTypes.size()+1];
        		int i = 1;
        		for (SecondType SecondType : SecondTypes) {
					names[i] = SecondType.getSchNum();
				}
        		return names;
        	}
        	String[] names = getNames();
            public int getSize() { return names.length; }
            public Object getElementAt(int i) { return names[i]; }
        });
        jList1.setSelectedIndex(1);
        jScrollPane2.setViewportView(jList1);

        jButton1.setText("添加用户"); 

        jButton2.setText("删除用户");

        jButton3.setText("用户详情");

        jButton4.setText("修改用户");

        jButton5.setText("返回菜单");
        
        
        jButton3.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent e)
			{
				view();
			}
		});
        
        jButton4.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent e)
			{
				update();
			}
		});
        
        jButton2.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent e)
			{
				delete();
			}
		});
        
        jButton1.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
				add();
			}
		});
        
        jButton5.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
				back();
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        
        this.setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents


    protected void view()
	{
    	String name = (String) jList1.getSelectedValue();
		this.dispose();
		List<SecondType> SecondTypes = SecondTypeDao.listQuery(" schNum = ? ", new Object[]{name}, null, null);
		ViewMember.SecondType = SecondTypes.get(0);
		new ViewMember();
	}


	protected void update()
	{
    	String name = (String) jList1.getSelectedValue();
		this.dispose();
		EditMember.SecondType = SecondTypeDao.getSecondTypeBySchnum(name);
		new EditMember();
	}


	protected void delete()
	{
		String name = (String) jList1.getSelectedValue();
		SecondTypeDao.remove(name);
		this.dispose();
		new MemberManageFrame();
	}


	protected void add()
	{
		this.dispose();
		EditMember.SecondType = new SecondType();
		new EditMember();
	}

	protected void back()
	{
		this.dispose();
		new MenuFrame();
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
