/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui.product;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.entity.Product;

/**
 *
 * @author Administrator
 */
public class EditProduct extends javax.swing.JFrame {

    public static Product Product = new Product();
	/**
     * Creates new form EditMember
     */
    public EditProduct() {
    	super("队员");
        initComponents();
    }
    
    private String getSex(int sex)
    {
    	if(sex == 0)
    	{
    		return "女";
    	}
    	return "男";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("姓名：");

        jLabel2.setText("性别：");

        jLabel3.setText("年龄：");

        jLabel4.setText("电话：");

        jLabel5.setText("邮箱：");

        jLabel6.setText("队名：");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "男", "女" }));
        
//        TeamService teamService = new TeamService();
//        String[] teams = teamService.getNames();
        
//        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(teams));

        jButton1.setText("确定");

        jButton2.setText("取消");
        
//        if(StringUtil.isNotBlank(member.getName()))
//        {
//        	jTextField1.setText(member.getName());
//        	
//        	jComboBox1.setSelectedItem(getSex(member.getSex()));
//        	
//        	jTextField3.setText(member.getAge()+"");
//        	jTextField4.setText(member.getPhone());
//        	jTextField5.setText(member.getEmail());
//        	Team team = EditMember.member.getTeam();
//        	if(null == team)
//        	{
//        		jComboBox2.setSelectedItem("未分组");
//        	}
//        	else
//        	{
//        		jComboBox2.setSelectedItem(team.getName());
//        	}
//        }

        
        jButton1.addActionListener(new ActionListener()
		{
			
			public void actionPerformed(ActionEvent arg0)
			{
//				commit();
			}
		});
        
        jButton2.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				back();
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
        
        this.setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

//    protected void commit()
//	{
//    	String name = jTextField1.getText().trim();
//    	String sex = (String) jComboBox1.getSelectedItem();
//    	String age = jTextField3.getText().trim();
//    	String phone = jTextField4.getText().trim();
//    	String email = jTextField5.getText().trim();
//    	
//    	if(StringUtil.isBlank(name) || StringUtil.isBlank(age) || StringUtil.isBlank(phone) || StringUtil.isBlank(email))
//    	{
//    		JOptionPane.showMessageDialog(this, "请将信息填完整！", "错误提示", JOptionPane.ERROR_MESSAGE);
//    		return;
//    	}
//    	int intAge = StringUtil.String2Int(age);
//    	if(StringUtil.ageIsOutOfSize(intAge))
//    	{
//    		JOptionPane.showMessageDialog(this, "年龄超出范围！", "错误提示", JOptionPane.ERROR_MESSAGE);
//    		return;
//    	}
//    	int intSex = 0;
//    	if("男".equals(sex))
//    	{
//    		intSex = 1;
//    	}
//    	if(!StringUtil.isEmail(email))
//    	{
//    		JOptionPane.showMessageDialog(this, "请输入正确的邮箱!", "错误提示", JOptionPane.ERROR_MESSAGE);
//    		return;
//    	}
//    	if(!StringUtil.isMobileNO(phone))
//    	{
//    		JOptionPane.showMessageDialog(this, "请输入正确的手机号!", "错误提示", JOptionPane.ERROR_MESSAGE);
//    		return;
//    	}
//    	if(nameIsExist(name) && StringUtil.isBlank(EditMember.member.getName()))
//    	{
//    		JOptionPane.showMessageDialog(this, "队员名字存在重复，请取一个别名!", "错误提示", JOptionPane.ERROR_MESSAGE);
//    		return;
//    	}
//    	
//    	Member member = new Member();
//    	member.setAge(intAge);
//    	member.setName(name);
//    	member.setEmail(email);
//    	member.setPhone(phone);
//    	member.setSex(intSex);
//    	
//    	TeamService teamService = new TeamService();
//    	Team team = teamService.get((String)jComboBox2.getSelectedItem());
//    	member.setTeam(team);
//    	
//    	MemberService memberService = new MemberService();
//    	
//    	if(StringUtil.isNotBlank(EditMember.member.getName()))
//    	{
//    		memberService.update(EditMember.member.getId(),member);
//    		JOptionPane.showMessageDialog(this, "修改队员成功!", "成功", JOptionPane.INFORMATION_MESSAGE);
//    		this.dispose();
//    		new MemberManageFrame();
//    	}
//    	else
//    	{
//    		memberService.add(member);
//    		JOptionPane.showMessageDialog(this, "添加队员成功!", "成功", JOptionPane.INFORMATION_MESSAGE);
//    		this.dispose();
//    		new MemberManageFrame();
//    	}
//    	
//	}
    
    /**
     * 名字存在返回true
     * @param name
     * @return
     */
    private boolean nameIsExist(String name)
    {
//    	MemberService memberService = new MemberService();
//    	String[] names = memberService.getNames();
//    	for (String string : names)
//		{
//			if(string.equals(name))
//			{
//				return true;
//			}
//		}
    	return false;
    }

	protected void back()
	{
		this.dispose();
//		new MemberManageFrame();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
